<?php if($_key = Mage::getStoreConfig('ve_interactive/settings/key')): ?>
<script type="text/javascript">
    !function () {
        var a = document.createElement("script");
        a.type = "text/javascript", a.async = !0, a.src = "//config1.veinteractive.com/tags/<?php echo str_replace('-', '/', $_key); ?>/tag.js";
        var b = document.getElementsByTagName("head")[0];
        if (b)b.appendChild(a, b); else {
            var b = document.getElementsByTagName("script")[0];
            b.parentNode.insertBefore(a, b)
        }
    }();
</script>
<?php endif; ?>